version: "3.8"

services:
    api-nginx:
        image: ${REGISTRY:-localhost}/market:nginx-cache
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/development/nginx/Dockerfile
            cache_from:
                -   ${REGISTRY}/market:nginx-cache
        ports:
            - "90:90"
        volumes:
            - ./:/app
        depends_on:
            - api-php-fpm
        networks:
            - marketplace

    api-php-fpm:
        image: ${REGISTRY:-localhost}/market:api-php-fpm:-ache
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/development/php-fpm/Dockerfile
            cache_from:
                -   ${REGISTRY}/market:api-php-fpm-cache
        volumes:
            - ./:/app:rw
        user: "1000:1000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - marketplace
        expose:
            - "9000"

    php-cli:
        image: ${REGISTRY:-localhost}/market:php-cli-cache
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/development/php-cli/Dockerfile
            cache_from:
                -   ${REGISTRY}/market:php-cli-cache
        volumes:
            - ./:/app
        working_dir: /app
        networks:
            - marketplace
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        container_name: marketplace-db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5440:5432"
        networks:
            - marketplace


networks:
    marketplace:
        driver: bridge

volumes:
    dbdata:
        driver: local
