version: "3.8"

services:
    api-nginx:
        image: ${REGISTRY}/nginx:${IMAGE_TAG}
        restart: always
        ports:
            - "85:85"
        depends_on:
            - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/api-php-fpm:${IMAGE_TAG}
        restart: always
        user: "${UID}:${GID}"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false

    php-cli:
        image: ${REGISTRY}/php-cli:${IMAGE_TAG}
        restart: always
        user: "${UID}:${GID}"

    db:
        image: postgres:16-alpine
        container_name: marketplace_postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5434:5434"
