version: "3.8"

services:
    api-nginx:
        container_name: api-nginx
        restart: unless-stopped
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "85:85"
        volumes:
            - ./:/app
        depends_on:
            - api-php-fpm
        networks:
            - marketplace

    api-php-fpm:
        container_name: api-php-fpm
        restart: unless-stopped
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./:/app
        user: "1000:1000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - marketplace
        expose:
            - "9000"

    php-cli:
        container_name: php-cli
        restart: unless-stopped
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./:/app
        user: "1000:1000"
        networks:
            - marketplace
        expose:
            - "9000"

    db:
        image: postgres:16-alpine
        container_name: marketplace_postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5434:5434"
        networks:
            - marketplace


networks:
    marketplace:
        driver: bridge

volumes:
    dbdata:
        driver: local
