name: Pipline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4

          - name: Install Docker & Docker Compose
            run: |
              sudo apt-get update
              sudo apt-get install -y docker-compose

          - name: Cache API composer
            uses: actions/cache@v2
            with:
              path: vendor
              key: api-composer-${{ hashFiles('composer.lock') }}

          - name: Dev init
            run: make init
