name: Pipline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    REGISTRY: ${{ secrets.REGISTRY }}

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4

          - name: Install Docker & Docker Compose
            run: |
              sudo apt-get update
              sudo apt-get install -y docker-compose

          - name: Cache API composer
            uses: actions/cache@v4
            with:
              path: vendor
              key: api-composer-${{ hashFiles('composer.lock') }}

          - name: Docker login
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Dev init
            run: make init

          - name: Push dev cache images
            run: make push-dev-cache
